apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
<<<<<<< HEAD
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    owner: jenkins-x-quickstarts
    repository: node-http
  name: jenkins-x-quickstarts-node-http-nm6dx-1
=======
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/4a22dee8a67f66e5012729808de081d2f4d0e715/tasks/git-clone/git-clone-pr.yaml
  creationTimestamp: null
  name: release
>>>>>>> update .lighthouse (https://github.com/jenkins-x/jx3-pipeline-catalog) from master (6b21c9efd838e04206df1e5b6ccc7cc62b224bf6) to master (0c94850790a73e4950f6fd63ef001e027c57f450)
spec:
  pipelineSpec:
    params:
    - default: master
      description: git revision to checkout (branch, tag, sha, ref…)
      name: revision
      type: string
    tasks:
    - name: from-build-pack
      params:
      - name: revision
        value: $(params.revision)
      resources: {}
      taskSpec:
        metadata: {}
        params:
        - default: master
          description: git revision to checkout (branch, tag, sha, ref…)
          name: revision
          type: string
        stepTemplate:
          env:
          - name: PIPELINE_KIND
            value: release
          - name: JX_BATCH_MODE
            value: "true"
          - name: VERSION
            value: $(inputs.params.version)
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          volumeMounts:
          - mountPath: /home/jenkins
            name: workspace-volume
          - mountPath: /etc/podinfo
            name: podinfo
            readOnly: true
          workingDir: /workspace/source
        steps:
        - args:
<<<<<<< HEAD
          - -c
          - 'mkdir -p $HOME; git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot};
            git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com};
            git config --global credential.helper store; git clone $(inputs.params.REPO_URL)
            $(inputs.params.subdirectory); echo cloned url: $(inputs.params.REPO_URL)
            to dir: $(inputs.params.subdirectory); cd $(inputs.params.subdirectory);
            git checkout $(inputs.params.revision); echo checked out revision: $(inputs.params.revision)
            to dir: $(inputs.params.subdirectory)'
          command:
          - /bin/sh
          image: gcr.io/jenkinsxio/builder-jx:2.1.32-662
          name: git-clone
          resources: {}
          workingDir: /workspace
        - args:
          - gitops
          - git
          - setup
          - --namespace
          - jx-git-operator
          command:
          - jx
          image: gcr.io/jenkinsxio/jx-cli:latest
          name: git-setup
          resources: {}
          workingDir: /workspace
        - args:
          - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
          command:
          - /bin/sh
          - -c
          image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
          name: setup-builder-home
          resources: {}
        - args:
=======
>>>>>>> update .lighthouse (https://github.com/jenkins-x/jx3-pipeline-catalog) from master (6b21c9efd838e04206df1e5b6ccc7cc62b224bf6) to master (0c94850790a73e4950f6fd63ef001e027c57f450)
          - pr
          command:
          - make
          image: gcr.io/jenkinsxio/jx-cli:latest
          name: make-pr
          resources: {}
        volumes:
        - emptyDir: {}
          name: workspace-volume
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
<<<<<<< HEAD
  podTemplate:
    hostNetwork: false
    schedulerName: ""
=======
  podTemplate: {}
>>>>>>> update .lighthouse (https://github.com/jenkins-x/jx3-pipeline-catalog) from master (6b21c9efd838e04206df1e5b6ccc7cc62b224bf6) to master (0c94850790a73e4950f6fd63ef001e027c57f450)
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
